import type { Report } from "@/app/page"

export const sampleReports: Report[] = [
  {
    id: "1",
    type: "bache",
    address: "Av. Corrientes 1234, Buenos Aires, Argentina",
    description:
      "Bache grande en el carril derecho que dificulta el tránsito vehicular y puede causar daños a los vehículos",
    latitude: -34.6037,
    longitude: -58.3816,
    votes: 12,
    created_at: new Date().toISOString(),
    reporter_name: "Juan Pérez",
  },
  {
    id: "2",
    type: "luz",
    address: "Calle Florida 567, Buenos Aires, Argentina",
    description: "Luminaria rota desde hace una semana, genera inseguridad durante la noche",
    latitude: -34.602,
    longitude: -58.375,
    votes: 8,
    created_at: new Date(Date.now() - 86400000).toISOString(),
    reporter_name: "María González",
  },
  {
    id: "3",
    type: "basura",
    address: "Plaza San Martín, Buenos Aires, Argentina",
    description: "Acumulación de basura en la esquina, genera malos olores y atrae roedores",
    latitude: -34.598,
    longitude: -58.38,
    votes: 15,
    created_at: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: "4",
    type: "inseguridad",
    address: "Av. Santa Fe 890, Buenos Aires, Argentina",
    description: "Zona con poca iluminación donde han ocurrido varios robos en las últimas semanas",
    latitude: -34.595,
    longitude: -58.385,
    votes: 23,
    created_at: new Date(Date.now() - 259200000).toISOString(),
    reporter_name: "Carlos Rodríguez",
  },
  {
    id: "5",
    type: "otro",
    address: "Calle Lavalle 456, Buenos Aires, Argentina",
    description: "Semáforo intermitente que no funciona correctamente, causa problemas de tránsito",
    latitude: -34.608,
    longitude: -58.378,
    votes: 6,
    created_at: new Date(Date.now() - 345600000).toISOString(),
  },
  {
    id: "6",
    type: "bache",
    address: "Av. 9 de Julio 123, Buenos Aires, Argentina",
    description: "Múltiples baches en la avenida principal que afectan el tránsito diario",
    latitude: -34.61,
    longitude: -58.383,
    votes: 31,
    created_at: new Date(Date.now() - 432000000).toISOString(),
    reporter_name: "Ana López",
  },
  {
    id: "7",
    type: "luz",
    address: "Parque Centenario, Buenos Aires, Argentina",
    description: "Varias luminarias del parque no funcionan, creando zonas muy oscuras",
    latitude: -34.606,
    longitude: -58.432,
    votes: 18,
    created_at: new Date(Date.now() - 518400000).toISOString(),
  },
  {
    id: "8",
    type: "basura",
    address: "Av. Rivadavia 2000, Buenos Aires, Argentina",
    description: "Contenedores desbordados que no se vacían hace días",
    latitude: -34.609,
    longitude: -58.392,
    votes: 9,
    created_at: new Date(Date.now() - 604800000).toISOString(),
    reporter_name: "Luis Martínez",
  },
]
